# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mi_tienda', '0002_auto_20190330_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la pelicula')),
                ('release_date', models.DateField(verbose_name='Fecha de estreno')),
                ('rate_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Veces que se ha calificado la pelicula')),
                ('rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de calificacion de la pelicula')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_tienda.Director')),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la lista')),
                ('movies', models.ManyToManyField(to='mi_tienda.Movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre del tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Camiseta',
        ),
        migrations.DeleteModel(
            name='zapatillas',
        ),
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_tienda.Studio'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(to='mi_tienda.Tag'),
        ),
    ]
