# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0003_auto_20190401_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del abrigo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca del abrigo')),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Camiseta_Futbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la camiseta')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca de la camiseta')),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chaqueta_Chandal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la chaqueta')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca de la chaqueta')),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='movielist',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
