# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0004_auto_20190403_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta_futbol',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
        ),
    ]
