# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0005_camiseta_futbol_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrigo',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
        ),
        migrations.AddField(
            model_name='chaqueta_chandal',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
        ),
    ]
