# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0006_auto_20190403_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrigo',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='camiseta_futbol',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chaqueta_chandal',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
