# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0008_auto_20190404_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaqueta_chandal',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre de la chaqueta'),
        ),
    ]
